set(_CATKIN_CURRENT_PACKAGE "filtro_particulas_kld")
set(filtro_particulas_kld_MAINTAINER "au <au@todo.todo>")
set(filtro_particulas_kld_DEPRECATED "")
set(filtro_particulas_kld_VERSION "0.0.0")
set(filtro_particulas_kld_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(filtro_particulas_kld_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(filtro_particulas_kld_BUILDTOOL_DEPENDS "catkin")